[window]

padding.x = 10
padding.y = 10

[font]

normal = { family = "SF Mono", style = "Regular" }
bold = { family = "SF Mono", style = "Bold" }

size = 27.5

[general]
import = ["themes/bm-dim.toml"]
